ui <- dashboardPage(
  dashboardHeader(title = "Credit Card Fraud Detection"),
  dashboardSidebar(  sidebarMenu(
    menuItem("EDA", tabName = "EDA", icon = icon("th")),
    menuItem("Model Metrics", icon = icon("th"), tabName = "Metrics"),
    menuItem("Working Model", icon = icon("th"), tabName = "Working")
  )),
  dashboardBody(
    
    tabItems(
      tabItem(tabName = "EDA",
              selectInput(inputId = "sel_SalesRep",
                          label = "Choose Parameters - USER ANALYTICS",
                          list("Age","FICO")),
              splitLayout(cellWidths = c("50%", "50%"),
                          plotOutput("plot"),
                          plotOutput("plot1"),
              ),
              selectInput(inputId = "sel_user",
                          label = "Choose Parameters - ANALYTICS",
                          list("Gender","State","Year")),
                          plotOutput("plot7"),
              h4(strong("CARD ANALYTICS")),
              splitLayout(cellWidths = c("50%", "50%"),
                          plotOutput("plot2"),
                          plotOutput("plot3"),
              ),
              selectInput(inputId = "sel_fraud",
                          label = "Choose Parameters - FRAUD ANALYTICS",
                          list("Merchant Number","Month","State")),
              splitLayout(cellWidths = c("50%", "50%"),
                          h6(strong("Number of Fraudulent Transactions")),
                          h6(strong("Average Fraudulent Amount")),
              ),
              splitLayout(cellWidths = c("50%", "50%"),
                          plotOutput("plot4"),
                          plotOutput("plot5"),
              ),
      ),
      
      tabItem(tabName = "Metrics",
            selectInput(inputId = "sampling",
                        label = "Choose Sampling ",
                        list("Sampling","No-Sampling")),
            selectInput(inputId = "metrics",
                        label = "Choose Metrics ",
                        list("Accuracy","Precision","F1-Score","Recall")),
            plotOutput("plot6")
      ),
      tabItem(tabName = "Working",
              splitLayout(cellWidths = c("25%", "25%", "25%", "25%"),
                textInput("change_prev", h6("change_prev")),
                selectInput(inputId = "above_moving_avg",
                            label = "Choose above_moving_avg ",
                            list("0","1")),
                selectInput(inputId = "above_max",
                            label = "Choose above_max ",
                            list("0","1")),
                selectInput(inputId = "change_prev_100perc_flag",
                            label = "Choose change_prev_100perc_flag ",
                            list("0","1")),
              ),
              br(),
              br(),
              splitLayout(cellWidths = c("25%", "25%", "25%", "25%"),
                          selectInput(inputId = "change_prev_200perc_flag",
                                      label = "Choose change_prev_200perc_flag ",
                                      list("0","1")),
                          selectInput(inputId = "same_merchant_transact",
                                      label = "Choose same_merchant_transact ",
                                      list("0","1")),
                          selectInput(inputId = "above_moving_avg_user_flag",
                                      label = "Choose above_moving_avg_user_flag ",
                                      list("0","1")),
                          selectInput(inputId = "mcc_risky",
                                      label = "Choose mcc_risky ",
                                      list("0","1")),
              ),
              br(),
              br(),
              br(),
              splitLayout(cellWidths = c("25%", "25%", "25%"),
                          selectInput(inputId = "type",
                                      label = "Choose Transaction Type",
                                      list("chip","swipe", "online")),
                          selectInput(inputId = "state_risky",
                                      label = "Choose state_risky ",
                                      list("0","1")),
                          selectInput(inputId = "age_risky",
                                      label = "Choose age_risky ",
                                      list("0","1")),
              ),
              actionButton("predict", "Predict Fraud", class = "btn-success"),
              textOutput("pred")
      )
    )
   
  ))